package com.pawfectfoods.trades.error;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_USER_DISABLED,
    AUTH_EMAIL_NOT_VERIFIED,
    VALIDATION_FAILED,
    VENDOR_ALREADY_EXISTS,
    VENDOR_NOT_FOUND,
    SUBVENDOR_LIMIT_EXCEEDED,
    TRADE_ALREADY_EXISTS,
    TRADE_NOT_FOUND,
    TRADE_NOTIFICATION_INVALID_SELECTION,
    FILE_INVALID_TYPE,
    FILE_TOO_LARGE,
    FILE_STORAGE_ERROR,
    USER_NOT_FOUND,
    CONFLICT,
    NOT_FOUND,
    FORBIDDEN,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR
}
